theme: jekyll-theme-minimal
description: Blog o IT oraz IOT
logo: "images/logo.png"
title: My kind of IT
relative_links:
  enabled:     true
  collections: false
footer:
  links:
    - label: "Ogłoszenia nieruchomości"
      url: "https://adresowo.pl/"
